name: "Fetch API Environment Variables"
description: "Retrieves API secrets from AWS SSM and writes them to .env"

inputs:
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  aws-region:
    description: "AWS Region"
    default: "us-east-1"

runs:
  using: "composite"
  steps:
    - name: Install AWS CLI (if not available)
      run: |
        if ! command -v aws &> /dev/null; then
          echo "AWS CLI not found, installing..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscli.zip"
          unzip awscli.zip
          sudo ./aws/install
        fi
      shell: bash

    - name: Configure AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ inputs.aws-access-key-id }}
        aws configure set aws_secret_access_key ${{ inputs.aws-secret-access-key }}
        aws configure set region ${{ inputs.aws-region }}
      shell: bash

    - name: Pull API environment variables
      run: |
        aws ssm get-parameter \
          --name drivers-license-api-staging-env \
          --with-decryption \
          --output text \
          --query Parameter.Value \
          --region ${{ inputs.aws-region }} > docker/.env
        echo ".env file successfully written with $(wc -l < .env) lines"
      shell: bash
