- name: Get environment variables from AWS SSM
  uses: eliasjcjunior/aws-ssm-parameters-action@1.2.2
  with:
    paths: "/my-app/env"
    recursive: true
    with-decryption: true
    split-env: true
    upper-case: false
    env-prefix: ""

- name: Save all parameters to .env file
  run: |
    env | grep '^AWS_' | sed -E 's/^AWS_([^=]+)=(.*)/\1=\2/' > .env
    cat .env  # Optional: Debugging to verify contents
