name: Build and Deploy DL API [STAGING]

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init
      - name: Plan Terraform Changes
        run: |
          cd terraform
          terraform plan -out=tfplan
          
      - name: Apply Terraform (Only If Changes Exist)
        run: |
          cd terraform
          terraform apply -auto-approve tfplan

      - name: Get EC2 Public IP
        run: |
          terraform output -raw ec2_public_ip | tr -d '\r' > ec2_ip.txt
          echo "EC2_IP=$(cat ec2_ip.txt)" >> $GITHUB_ENV



      - name: Pull API environment variables
        run: |
          touch .env
          aws --region us-east-1 ssm get-parameter --name drivers-license-api-staging-env --output text --query Parameter.Value >> .env
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << 'EOF'
          cd /home/ubuntu/app
          git pull origin main
          sudo docker-compose up --env-file .env -d --build
          EOF
