name: Build and Deploy DL API [STAGING]

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull API environment variables
        run: |
          touch .env
          aws --region us-east-1 ssm get-parameter --name drivers-license-api-staging-env --output text --query Parameter.Value >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}
          
      - name: Build and Push Docker Image
        run: |
          docker build -t api -f docker/Dockerfile .
          docker tag api:latest ${{ secrets.AWS_ECR_URL }}/api:latest
          docker push ${{ secrets.AWS_ECR_URL }}/api:latest

          
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Deploy to EC2 via SSH
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ubuntu/
          scp -i ~/.ssh/id_rsa .env ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/.env
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}
          docker pull ${{ secrets.AWS_ECR_URL }}/api:latest
          sudo docker-compose up --env-file .env -d --build
          EOF
        env:
          EC2_IP: ${{ secrets.EC2_IP }}

